### ISSUE TITLE
Avatar decoration misaligned

### ISSUE THREAD

**Issue by sirhvd** [VeivVovii/Nocturnal-discord-theme#1]
![image](https://github.com/VeivVovii/Nocturnal-discord-theme/assets/8132142/57cdb1cd-3954-4295-9da4-a719cf8663ca)

Temporary fix by adding:

```css
.avatarDecoration__8a0c2 {
    left: 16px !important;
}
```
